export type BreedCategory = "chien" | "chat";
export type BreedSize = "tres-petit" | "petit" | "moyen" | "grand" | "tres-grand";
export type CareLevel = "facile" | "modere" | "exigeant" | "tres-exigeant";
export type ExerciseNeeds = "faible" | "modere" | "eleve" | "tres-eleve";
export type GroomingFrequency = "minimal" | "mensuel" | "hebdomadaire" | "quotidien";
export type Prevalence = "frequente" | "moderee" | "rare";

export interface BreedDisease {
  name: string;
  prevalence: Prevalence;
  description: string;
  preventionTip: string;
}

export interface BreedProfile {
  slug: string;
  name: string;
  category: BreedCategory;
  origin: string;
  size: BreedSize;
  weightMale: { min: number; max: number };
  weightFemale: { min: number; max: number };
  heightMale?: { min: number; max: number }; // cm au garrot
  lifespanMin: number;
  lifespanMax: number;
  temperament: string[];
  commonDiseases: BreedDisease[];
  careLevel: CareLevel;
  exerciseNeeds: ExerciseNeeds;
  groomingFrequency: GroomingFrequency;
  apartmentFriendly: boolean;
  goodWithChildren: boolean;
  goodWithOtherPets: boolean;
  recognizedBy: string[];
  photo: string; // Unsplash URL (without params)
  description: string; // 2 paragraphs joined with \n\n
  relatedArticleSlugs: string[];
  publishedAt: string;
  lastUpdatedAt: string;
}

export const BREEDS: BreedProfile[] = [
  // ══ CHIENS ═══════════════════════════════════════════════════════════════

  {
    slug: "labrador-retriever",
    name: "Labrador Retriever",
    category: "chien",
    origin: "Canada (Terre-Neuve) / Angleterre",
    size: "grand",
    weightMale: { min: 29, max: 36 },
    weightFemale: { min: 25, max: 32 },
    heightMale: { min: 56, max: 62 },
    lifespanMin: 10,
    lifespanMax: 14,
    temperament: ["Amical", "Actif", "Docile", "Joueur", "Confiant", "Agréable"],
    commonDiseases: [
      { name: "Dysplasie de la hanche", prevalence: "frequente", description: "Malformation articulaire héréditaire affectant jusqu'à 20% des Labradors. Entraîne boiterie et arthrose précoce.", preventionTip: "Acheter auprès d'éleveurs testant leurs reproducteurs (HD A/B). Éviter la suralimentation chez le chiot." },
      { name: "Dysplasie du coude", prevalence: "frequente", description: "Anomalie de développement du coude, souvent bilatérale. Se manifeste entre 5 et 12 mois par boiterie antérieure.", preventionTip: "Test radiographique des reproducteurs (score OFA/BVA). Croissance contrôlée." },
      { name: "Obésité", prevalence: "frequente", description: "Le Labrador manque du gène POMC (satiété) — particulièrement enclin à l'obésité, aggravant les problèmes articulaires et cardiaques.", preventionTip: "Peser les rations, éviter les friandises, exercice quotidien modéré." },
      { name: "Hépatotoxicité au carprofène", prevalence: "moderee", description: "Prédisposition génétique à l'hépatotoxicité idiosyncrasique lors de traitement AINS (carprofène/Rimadyl).", preventionTip: "Suivi hépatique (ALAT) avant et pendant tout traitement au carprofène." },
    ],
    careLevel: "facile",
    exerciseNeeds: "eleve",
    groomingFrequency: "hebdomadaire",
    apartmentFriendly: false,
    goodWithChildren: true,
    goodWithOtherPets: true,
    recognizedBy: ["FCI", "LOF"],
    photo: "https://images.unsplash.com/photo-1633722715463-d30628ceb4f9",
    description: "Le Labrador Retriever est la race de chien la plus populaire dans le monde depuis plusieurs décennies. Originaire de Terre-Neuve au Canada, il a été développé en Angleterre au XIXe siècle pour assister les pêcheurs puis comme chien de chasse rapporteur. Il existe en trois couleurs officielles : jaune, chocolat et noir.\n\nDoté d'un caractère exceptionnel, le Labrador est réputé pour sa douceur, son intelligence et sa facilité d'éducation. C'est pour ces raisons qu'il est le chien guide pour aveugles et chien d'assistance par excellence. Sa gourmandise légendaire (liée à une mutation du gène POMC) nécessite une gestion rigoureuse de l'alimentation pour prévenir l'obésité.",
    relatedArticleSlugs: ["dysplasie-hanche-chien-labrador", "obésite-chien-prevention"],
    publishedAt: "2024-01-10",
    lastUpdatedAt: "2026-01-10",
  },
  {
    slug: "berger-allemand",
    name: "Berger Allemand",
    category: "chien",
    origin: "Allemagne",
    size: "grand",
    weightMale: { min: 30, max: 40 },
    weightFemale: { min: 22, max: 32 },
    heightMale: { min: 60, max: 65 },
    lifespanMin: 9,
    lifespanMax: 13,
    temperament: ["Courageux", "Loyal", "Obéissant", "Curieux", "Confiant", "Alert"],
    commonDiseases: [
      { name: "Dysplasie de la hanche", prevalence: "frequente", description: "Particulièrement prévalente dans la race, la forme couchante du Berger Allemand accentue les contraintes sur les articulations.", preventionTip: "Test radiographique obligatoire des reproducteurs (HD A ou B)." },
      { name: "Myélopathie dégénérative (DM)", prevalence: "frequente", description: "Maladie neurologique progressive touchant la moelle épinière, conduisant à une paralysie progressive des membres postérieurs. Incurable.", preventionTip: "Test génétique disponible (mutation SOD1). Éviter d'accoupler deux porteurs." },
      { name: "Dilatation-torsion de l'estomac", prevalence: "moderee", description: "Urgence vitale. L'estomac se dilate et peut se tordre, entraînant un choc endotoxinique mortel en quelques heures.", preventionTip: "Fractionner les repas (2-3 fois/jour), éviter l'exercice dans l'heure post-repas. Gastropexie préventive possible." },
      { name: "Pannus (kératite superficielle chronique)", prevalence: "moderee", description: "Inflammation immuno-médiée de la cornée, aggravée par l'exposition UV. Peut conduire à la cécité si non traité.", preventionTip: "Lunettes de protection pour chiens vivant en altitude. Traitement médical au long cours (ciclosporine oculaire)." },
    ],
    careLevel: "modere",
    exerciseNeeds: "tres-eleve",
    groomingFrequency: "hebdomadaire",
    apartmentFriendly: false,
    goodWithChildren: true,
    goodWithOtherPets: true,
    recognizedBy: ["FCI", "LOF"],
    photo: "https://images.unsplash.com/photo-1618836283060-80ba0bcf0fe4",
    description: "Le Berger Allemand est l'une des races canines les plus polyvalentes et les plus utilisées dans le monde. Développé en Allemagne à la fin du XIXe siècle par Max von Stephanitz, il excelle dans le travail policier, militaire, la recherche et sauvetage, l'assistance et le sport canin (Schutzhund).\n\nIntelligent et volontaire, il requiert une stimulation mentale et physique importante. Un Berger Allemand sous-stimulé peut développer des comportements destructeurs ou anxieux. Son éducation doit débuter tôt avec des méthodes positives et une socialisation intensive.",
    relatedArticleSlugs: ["myelopathie-degenerative-chien", "dilation-torsion-estomac-urgence"],
    publishedAt: "2024-01-10",
    lastUpdatedAt: "2026-01-10",
  },
  {
    slug: "golden-retriever",
    name: "Golden Retriever",
    category: "chien",
    origin: "Écosse / Angleterre",
    size: "grand",
    weightMale: { min: 29, max: 34 },
    weightFemale: { min: 25, max: 29 },
    heightMale: { min: 56, max: 61 },
    lifespanMin: 10,
    lifespanMax: 12,
    temperament: ["Fiable", "Confiant", "Aimable", "Patient", "Intelligent", "Doux"],
    commonDiseases: [
      { name: "Cancer", prevalence: "frequente", description: "Le Golden Retriever présente une prévalence de cancer exceptionnellement élevée (~60% décèdent d'un cancer). Hémangiosarcome, lymphome et tumeurs osseuses sont les plus fréquents.", preventionTip: "Surveillance vétérinaire semestrielle. Stérilisation après maturité sexuelle (réduirait certains risques)." },
      { name: "Dysplasie de la hanche", prevalence: "frequente", description: "Même problématique que chez le Labrador. Tests des reproducteurs indispensables.", preventionTip: "Radiographies des reproducteurs, croissance contrôlée, exercice adapté." },
      { name: "Dermatite atopique", prevalence: "frequente", description: "Prédisposition génétique marquée aux allergies cutanées et à la dermatite atopique.", preventionTip: "Alimentation hypoallergénique si signes cliniques, consultations dermatologiques vétérinaires." },
    ],
    careLevel: "modere",
    exerciseNeeds: "eleve",
    groomingFrequency: "hebdomadaire",
    apartmentFriendly: false,
    goodWithChildren: true,
    goodWithOtherPets: true,
    recognizedBy: ["FCI", "LOF"],
    photo: "https://images.unsplash.com/photo-1641887917694-97788dd4e196",
    description: "Le Golden Retriever est issu du croisement entre des chiens rapporteurs à poil plat et des Tweed Water Spaniels dans les Highlands écossais au XIXe siècle. Sa robe dorée, son caractère exceptionnel et sa polyvalence en ont fait l'une des races les plus appréciées au monde.\n\nD'une gentillesse remarquable, le Golden est idéal pour les familles avec enfants. Très utilisé comme chien guide et chien thérapeutique, il nécessite cependant une surveillance vétérinaire rigoureuse en raison de sa prédisposition exceptionnellement élevée aux cancers.",
    relatedArticleSlugs: ["cancer-chien-signes-precoces", "dermatite-atopique-chien-traitement"],
    publishedAt: "2024-01-15",
    lastUpdatedAt: "2026-01-10",
  },
  {
    slug: "border-collie",
    name: "Border Collie",
    category: "chien",
    origin: "Frontière Angleterre / Écosse",
    size: "moyen",
    weightMale: { min: 14, max: 20 },
    weightFemale: { min: 12, max: 18 },
    heightMale: { min: 48, max: 56 },
    lifespanMin: 12,
    lifespanMax: 15,
    temperament: ["Extrêmement intelligent", "Energique", "Alert", "Sensible", "Tenace", "Instinct pastoral fort"],
    commonDiseases: [
      { name: "Anomalie de l'œil du Colley (AOC)", prevalence: "frequente", description: "Malformation oculaire héréditaire pouvant aller de l'hypoplasie choroïdienne à la cécité. Présente chez jusqu'à 30% des Border Collies.", preventionTip: "Test génétique avant l'accouplement. Examen ophtalmologique systématique des chiots à 7-8 semaines." },
      { name: "Épilepsie idiopathique", prevalence: "moderee", description: "Prédisposition génétique à l'épilepsie. Les crises surviennent généralement entre 1 et 5 ans.", preventionTip: "Éviter les croisements entre chiens ayant des antécédents familiaux d'épilepsie." },
      { name: "Sensibilité MDR1 (ivermectine)", prevalence: "moderee", description: "Mutation du gène ABCB1 rendant le chien sensible à l'ivermectine et autres antiparasitaires (milbémycine à haute dose).", preventionTip: "Test génétique MDR1. Éviter l'ivermectine hors AMM. Utiliser des traitements antiparasitaires approuvés pour la race." },
    ],
    careLevel: "tres-exigeant",
    exerciseNeeds: "tres-eleve",
    groomingFrequency: "hebdomadaire",
    apartmentFriendly: false,
    goodWithChildren: true,
    goodWithOtherPets: true,
    recognizedBy: ["FCI", "LOF"],
    photo: "https://images.unsplash.com/photo-1503256207526-0d5523e1b843",
    description: "Le Border Collie est universellement reconnu comme le chien le plus intelligent du monde. Né pour rassembler les moutons le long de la frontière anglo-écossaise, il possède un instinct pastoral extraordinaire et une énergie presque inépuisable. Il excelle dans tous les sports canins : agility, frisbee, obéissance, flyball.\n\nMalgré ses qualités exceptionnelles, le Border Collie est inadapté à la vie d'appartement et à une famille sédentaire. Sans stimulation mentale et physique intensive, il peut développer des comportements compulsifs ou destructeurs. C'est un chien pour propriétaires expérimentés et actifs.",
    relatedArticleSlugs: ["border-collie-education-sport", "epilepsie-chien-que-faire-crise"],
    publishedAt: "2024-01-20",
    lastUpdatedAt: "2026-01-10",
  },
  {
    slug: "bulldog-francais",
    name: "Bouledogue Français",
    category: "chien",
    origin: "France (issu de bulldogs anglais miniatures)",
    size: "petit",
    weightMale: { min: 9, max: 14 },
    weightFemale: { min: 8, max: 12 },
    heightMale: { min: 27, max: 35 },
    lifespanMin: 10,
    lifespanMax: 14,
    temperament: ["Affectueux", "Joueur", "Alerte", "Adaptable", "Patient", "Têtu"],
    commonDiseases: [
      { name: "Syndrome brachycéphale (BOAS)", prevalence: "frequente", description: "Obstruction des voies respiratoires supérieures due à la morphologie de la tête. Sténose des narines, palais mou long, sténose trachéale. Peut nécessiter une chirurgie.", preventionTip: "Ne jamais acheter auprès d'éleveurs non testés. Éviter l'exercice par chaleur. Chirurgie corrective recommandée avant 2 ans." },
      { name: "Dermatite des plis cutanés", prevalence: "frequente", description: "Intertrigo humide et infestions bactériennes dans les plis de la peau du museau et du corps.", preventionTip: "Nettoyage quotidien des plis avec une solution antiseptique. Séchage soigneux." },
      { name: "Hernies intervertébrales (IVDD)", prevalence: "frequente", description: "Prédisposition à la hernie discale thoraco-lombaire. Peut provoquer paralysie des membres postérieurs.", preventionTip: "Éviter les sauts (canapé, escaliers). IRM annuel recommandé par certains vétérinaires spécialistes." },
      { name: "Atrésie anale / malformations congénitales", prevalence: "moderee", description: "Plusieurs malformations congénitales sont surreprésentées dans la race.", preventionTip: "Bilan de santé complet du chiot par un vétérinaire dès l'acquisition." },
    ],
    careLevel: "modere",
    exerciseNeeds: "faible",
    groomingFrequency: "hebdomadaire",
    apartmentFriendly: true,
    goodWithChildren: true,
    goodWithOtherPets: true,
    recognizedBy: ["FCI", "LOF"],
    photo: "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e",
    description: "Le Bouledogue Français est devenu en quelques années la race la plus populaire de France et l'une des plus populaires d'Europe. Compact, affectueux et adaptable, il convient parfaitement à la vie en appartement et aux citadins. Son caractère joueur et sa tendresse en font un excellent compagnon.\n\nMalheureusement, sa morphologie brachycéphale extrême engendre de sérieux problèmes de santé respiratoires (syndrome BOAS). Les propriétaires doivent choisir des éleveurs responsables testant leurs reproducteurs et s'engager dans un suivi vétérinaire régulier, notamment pour la correction chirurgicale si nécessaire.",
    relatedArticleSlugs: ["syndrome-brachycephale-chien-traitement", "bulldog-francais-soins"],
    publishedAt: "2024-02-01",
    lastUpdatedAt: "2026-01-10",
  },
  {
    slug: "berger-australien",
    name: "Berger Australien",
    category: "chien",
    origin: "États-Unis (malgré son nom)",
    size: "moyen",
    weightMale: { min: 25, max: 32 },
    weightFemale: { min: 16, max: 25 },
    heightMale: { min: 51, max: 58 },
    lifespanMin: 12,
    lifespanMax: 15,
    temperament: ["Intelligent", "Actif", "Loyal", "Protecteur", "Joueur", "Énergique"],
    commonDiseases: [
      { name: "Sensibilité MDR1 (ivermectine)", prevalence: "frequente", description: "Le Berger Australien présente une forte prévalence de la mutation ABCB1 — jusqu'à 50% des chiens sont affectés.", preventionTip: "Test génétique MDR1 indispensable. Éviter l'ivermectine et certains antiparasitaires. Mentionner au vétérinaire." },
      { name: "Épilepsie idiopathique", prevalence: "frequente", description: "Race surreprésentée pour l'épilepsie idiopathique héréditaire.", preventionTip: "Éviter les croisements entre chiens affectés. Traitement antiépileptique si nécessaire." },
      { name: "Anomalie de l'œil du Colley", prevalence: "moderee", description: "Comme le Border Collie, peut être porteur de cette anomalie héréditaire.", preventionTip: "Examen ophtalmologique systématique et test génétique." },
    ],
    careLevel: "exigeant",
    exerciseNeeds: "tres-eleve",
    groomingFrequency: "hebdomadaire",
    apartmentFriendly: false,
    goodWithChildren: true,
    goodWithOtherPets: true,
    recognizedBy: ["FCI", "LOF"],
    photo: "https://images.unsplash.com/photo-1601758123927-457b0c3a3a44",
    description: "Malgré son nom, le Berger Australien a été développé aux États-Unis par des bergers basques ayant transité par l'Australie. Il est devenu l'une des races de travail et de sport les plus populaires, notamment dans les disciplines d'agility et de frisbee.\n\nExtrêmement intelligent et polyvalent, l'Aussie est un chien de travail dans l'âme qui a besoin d'une occupation intellectuelle et physique quotidienne intense. Son instinct grégaire est fort — il peut « rassembler » les enfants ou d'autres animaux. Sa mutation MDR1 fréquente nécessite une vigilance particulière concernant les médicaments.",
    relatedArticleSlugs: ["mdr1-mutation-chien-medicaments-dangereux"],
    publishedAt: "2024-02-05",
    lastUpdatedAt: "2026-01-10",
  },
  {
    slug: "husky-siberien",
    name: "Husky Sibérien",
    category: "chien",
    origin: "Sibérie (Russie) — peuple Tchouktche",
    size: "moyen",
    weightMale: { min: 20, max: 27 },
    weightFemale: { min: 16, max: 23 },
    heightMale: { min: 54, max: 60 },
    lifespanMin: 12,
    lifespanMax: 14,
    temperament: ["Amical", "Espiègle", "Alert", "Sociable", "Indépendant", "Têtu"],
    commonDiseases: [
      { name: "Cataracte héréditaire", prevalence: "frequente", description: "Opacification du cristallin d'origine génétique, pouvant apparaître dès 2-3 ans.", preventionTip: "Test génétique des reproducteurs. Suivi ophtalmologique annuel." },
      { name: "Atrophie progressive de la rétine (APR)", prevalence: "moderee", description: "Dégénérescence progressive des photorécepteurs rétiniens, conduisant à la cécité.", preventionTip: "Test génétique PRCD obligatoire pour les reproducteurs." },
      { name: "Dermatite du zinc", prevalence: "moderee", description: "Syndrome de malabsorption du zinc entraînant des lésions cutanées autour des zones de friction.", preventionTip: "Supplémentation en zinc (sous contrôle vétérinaire). Alimentation de qualité." },
    ],
    careLevel: "exigeant",
    exerciseNeeds: "tres-eleve",
    groomingFrequency: "hebdomadaire",
    apartmentFriendly: false,
    goodWithChildren: true,
    goodWithOtherPets: true,
    recognizedBy: ["FCI", "LOF"],
    photo: "https://images.unsplash.com/photo-1605568427561-40dd23c2acea",
    description: "Le Husky Sibérien a été développé par le peuple Tchouktche en Sibérie pour tirer des traîneaux sur de longues distances dans des conditions arctiques extrêmes. Importé en Alaska au début du XXe siècle, il s'est distingué lors de la course de relais qui a inspiré l'Iditarod.\n\nAu caractère amical et sociable, le Husky ne fait pas un bon chien de garde mais est un compagnon jovial. Athlète né, il nécessite de l'exercice quotidien intensif. Son instinct de fuite est très fort — clôture sécurisée indispensable. Sa vocalisation distinctive (il hurle plus qu'il n'aboie) peut surprendre les voisins.",
    relatedArticleSlugs: ["husky-education-fugue", "atrophie-retine-chien-symptomes"],
    publishedAt: "2024-02-10",
    lastUpdatedAt: "2026-01-10",
  },
  {
    slug: "yorkshire-terrier",
    name: "Yorkshire Terrier",
    category: "chien",
    origin: "Angleterre (Yorkshire)",
    size: "tres-petit",
    weightMale: { min: 2, max: 3.2 },
    weightFemale: { min: 2, max: 3.2 },
    heightMale: { min: 18, max: 23 },
    lifespanMin: 13,
    lifespanMax: 16,
    temperament: ["Courageux", "Énergique", "Intelligent", "Affectueux", "Têtu", "Territorial"],
    commonDiseases: [
      { name: "Shunt porto-systémique", prevalence: "moderee", description: "Anomalie vasculaire hépatique congénitale. Le sang contourne le foie — accumulation de toxines. Symptômes : hypoglycémie, comportement anormal, crises neurologiques.", preventionTip: "Bilan hépatique et échographie chez le chiot si symptômes suspects. Chirurgie corrective possible." },
      { name: "Luxation de la rotule", prevalence: "frequente", description: "Luxation médiale fréquente dans les petites races. De grade 1 à 4 selon la sévérité.", preventionTip: "Surveillance du port des membres antérieurs. Chirurgie si grade 3-4." },
      { name: "Effondrement de la trachée", prevalence: "moderee", description: "Affaissement de la trachée causant une toux chronique « d'oie ». Aggravé par le stress, l'obésité et le collier.", preventionTip: "Utiliser un harnais (jamais un collier). Maintenir le poids idéal. Traitement médical voire chirurgical." },
    ],
    careLevel: "modere",
    exerciseNeeds: "modere",
    groomingFrequency: "quotidien",
    apartmentFriendly: true,
    goodWithChildren: true,
    goodWithOtherPets: true,
    recognizedBy: ["FCI", "LOF"],
    photo: "https://images.unsplash.com/photo-1618836283060-15e2a8a6e80f",
    description: "Le Yorkshire Terrier, malgré sa petite taille, possède la personnalité d'un grand chien. Développé dans le comté du Yorkshire en Angleterre pour chasser les rats dans les mines et les filatures textiles, il est devenu au fil du temps un chien de compagnie très prisé, notamment dans les milieux aristocratiques victoriens.\n\nVif, courageux et parfois dominateur, le Yorkshire est un terrier authentique qui ignore sa petite taille. Son pelage soyeux et long nécessite un entretien quotidien conséquent. Longévité remarquable pour un chien, il peut vivre jusqu'à 16-18 ans avec des soins adaptés.",
    relatedArticleSlugs: ["luxation-rotule-chien-traitement", "shunt-porto-systemique-chien"],
    publishedAt: "2024-02-15",
    lastUpdatedAt: "2026-01-10",
  },
  {
    slug: "chihuahua",
    name: "Chihuahua",
    category: "chien",
    origin: "Mexique (état de Chihuahua)",
    size: "tres-petit",
    weightMale: { min: 1.5, max: 3 },
    weightFemale: { min: 1.5, max: 3 },
    heightMale: { min: 15, max: 23 },
    lifespanMin: 12,
    lifespanMax: 18,
    temperament: ["Courageux", "Alert", "Vif", "Têtu", "Loyal", "Impulsif"],
    commonDiseases: [
      { name: "Luxation de la rotule", prevalence: "frequente", description: "Très fréquente dans la race. La petite taille et l'angulation des membres favorisent la luxation médiale de la rotule.", preventionTip: "Examen orthopédique annuel. Chirurgie si symptomatique (grades 3-4)." },
      { name: "Hydrocéphalie", prevalence: "moderee", description: "Accumulation de LCR dans les ventricules cérébraux. Plus fréquente dans les variétés à tête en forme de pomme (apple head).", preventionTip: "Examen neurologique systématique à l'acquisition. Éviter les chocs à la tête (os mou — fontanelle ouverte)." },
      { name: "Hypoglycémie du jeune chiot", prevalence: "frequente", description: "Chute soudaine de la glycémie, particulièrement chez les chiots et les adultes de très petit poids.", preventionTip: "Petits repas fréquents (3-4 fois/jour). En cas de prostration, miel sur les gencives et vétérinaire d'urgence." },
      { name: "Persistance du fontanelle", prevalence: "frequente", description: "Os du crâne qui ne se soudent pas complètement, laissant une zone molle sur le sommet du crâne.", preventionTip: "Zone à protéger des traumatismes. Neurologique si fontanelle trop large." },
    ],
    careLevel: "modere",
    exerciseNeeds: "faible",
    groomingFrequency: "minimal",
    apartmentFriendly: true,
    goodWithChildren: false,
    goodWithOtherPets: true,
    recognizedBy: ["FCI", "LOF"],
    photo: "https://images.unsplash.com/photo-1548199973-03664d76b856",
    description: "Le Chihuahua est la plus petite race de chien au monde, originaire du Mexique. Descendant probable du Techichi, chien des civilisations précolombiques, il a été popularisé au XIXe siècle dans l'État de Chihuahua. Il existe en deux variétés : à poil court et à poil long.\n\nDerrière sa petite taille se cache un tempérament affirmé et courageux. Le Chihuahua est profondément attaché à son propriétaire et peut être jaloux ou méfiant envers les étrangers. Son éducation ne doit pas être négligée sous prétexte de sa petite taille — le « syndrome du petit chien » (comportements dominants tolérés) lui nuit. Sa longévité exceptionnelle (jusqu'à 18 ans) en fait un engagement à long terme.",
    relatedArticleSlugs: ["hypoglycemie-chien-urgence", "luxation-rotule-chien-traitement"],
    publishedAt: "2024-02-20",
    lastUpdatedAt: "2026-01-10",
  },
  {
    slug: "rottweiler",
    name: "Rottweiler",
    category: "chien",
    origin: "Allemagne (Rottweil, Bade-Wurtemberg)",
    size: "grand",
    weightMale: { min: 50, max: 60 },
    weightFemale: { min: 35, max: 48 },
    heightMale: { min: 61, max: 68 },
    lifespanMin: 9,
    lifespanMax: 11,
    temperament: ["Loyal", "Courageux", "Confiant", "Calme", "Stoïque", "Protecteur"],
    commonDiseases: [
      { name: "Ostéosarcome", prevalence: "frequente", description: "Tumeur osseuse maligne très fréquente chez le Rottweiler, particulièrement aux membres distaux. Pronostic sombre.", preventionTip: "Surveillance des boiteries persistantes chez l'adulte. Radiographies diagnostiques." },
      { name: "Dysplasie de la hanche et du coude", prevalence: "frequente", description: "Race à forte prévalence de dysplasie, due à sa masse corporelle importante.", preventionTip: "Tests radiographiques des reproducteurs. Croissance contrôlée." },
      { name: "Myasthénie grave", prevalence: "moderee", description: "Maladie neuromusculaire auto-immune. Se manifeste par une faiblesse musculaire progressive et un méga-œsophage.", preventionTip: "Consultation neurologique si faiblesse musculaire anormale." },
    ],
    careLevel: "exigeant",
    exerciseNeeds: "eleve",
    groomingFrequency: "hebdomadaire",
    apartmentFriendly: false,
    goodWithChildren: true,
    goodWithOtherPets: true,
    recognizedBy: ["FCI", "LOF"],
    photo: "https://images.unsplash.com/photo-1567752881298-894bb81f9379",
    description: "Le Rottweiler descend des chiens de bouchers romains qui accompagnaient les légions lors de la conquête de l'Europe. À Rottweil, il servait à conduire le bétail et transporter les recettes des marchands. Aujourd'hui, il est principalement utilisé comme chien de travail policier et militaire, ainsi que chien de famille.\n\nD'une confiance et d'une loyauté remarquables, le Rottweiler est un chien imposant qui demande une socialisation précoce et une éducation ferme basée sur la relation de confiance. Son intelligence et son désir de plaire facilitent le dressage, mais son gabarit et sa force physique nécessitent un propriétaire expérimenté.",
    relatedArticleSlugs: ["osteosarcome-chien-symptomes"],
    publishedAt: "2024-03-01",
    lastUpdatedAt: "2026-01-10",
  },
  {
    slug: "teckel",
    name: "Teckel",
    category: "chien",
    origin: "Allemagne",
    size: "petit",
    weightMale: { min: 7, max: 15 },
    weightFemale: { min: 6, max: 15 },
    heightMale: { min: 20, max: 35 },
    lifespanMin: 12,
    lifespanMax: 16,
    temperament: ["Courageux", "Persistant", "Joueur", "Affectueux", "Têtu", "Alert"],
    commonDiseases: [
      { name: "Hernies intervertébrales (IVDD)", prevalence: "frequente", description: "Le Teckel est la race la plus prédisposée aux hernies discales en raison de sa chondrodystrophie. Le risque cumulatif sur une vie est de 25% environ.", preventionTip: "Éviter les escaliers et les sauts. Rampes d'accès aux meubles. IRM préventive conseillée après 3 ans dans les familles à risque." },
      { name: "Obésité", prevalence: "frequente", description: "Sa petite taille et son caractère glouton prédisposent à l'obésité, qui aggrave dramatiquement le risque de hernie discale.", preventionTip: "Peser les rations. Balances pour les croquettes. Pas d'excès de friandises." },
    ],
    careLevel: "modere",
    exerciseNeeds: "modere",
    groomingFrequency: "hebdomadaire",
    apartmentFriendly: true,
    goodWithChildren: true,
    goodWithOtherPets: true,
    recognizedBy: ["FCI", "LOF"],
    photo: "https://images.unsplash.com/photo-1535930749574-1399327ce78f",
    description: "Le Teckel (ou Dachshund en allemand — « blaireau chien ») a été développé en Allemagne pour chasser le blaireau et d'autres animaux terriers. Sa silhouette caractéristique — corps allongé sur pattes courtes — n'est pas un hasard mais une sélection délibérée pour lui permettre de s'introduire dans les terriers.\n\nPersonnalité espiègle et courageuse, le Teckel est un compagnon attachant mais têtu. Son caractère de terrier nécessite une éducation patiente et cohérente. Sa prédisposition aux hernies discales (IVDD) est un sujet de santé majeur qui mérite une prévention active tout au long de sa vie.",
    relatedArticleSlugs: ["hernie-discale-teckel-ivdd-traitement"],
    publishedAt: "2024-03-05",
    lastUpdatedAt: "2026-01-10",
  },
  {
    slug: "bichon-frise",
    name: "Bichon Frisé",
    category: "chien",
    origin: "Méditerranée (France / Belgique)",
    size: "petit",
    weightMale: { min: 3, max: 5 },
    weightFemale: { min: 3, max: 5 },
    heightMale: { min: 23, max: 30 },
    lifespanMin: 12,
    lifespanMax: 15,
    temperament: ["Gai", "Joueur", "Affectueux", "Sociable", "Adaptable", "Doux"],
    commonDiseases: [
      { name: "Allergies cutanées", prevalence: "frequente", description: "Dermatite atopique et allergies alimentaires fréquentes, se manifestant par du prurit, rougeurs et larmoiements.", preventionTip: "Alimentation hypoallergénique, bain régulier au shampoing doux, consultation dermatologique." },
      { name: "Luxation de la rotule", prevalence: "moderee", description: "Luxation médiale de la rotule commune dans les petites races.", preventionTip: "Surveiller la démarche. Chirurgie si grade 3-4." },
    ],
    careLevel: "modere",
    exerciseNeeds: "modere",
    groomingFrequency: "quotidien",
    apartmentFriendly: true,
    goodWithChildren: true,
    goodWithOtherPets: true,
    recognizedBy: ["FCI", "LOF"],
    photo: "https://images.unsplash.com/photo-1576087261849-a63fd3a0a3b7",
    description: "Le Bichon Frisé est un petit chien blanc au pelage bouclé et à la personnalité solaire. Descendant du Barbet, il s'est répandu autour de la Méditerranée et a connu un succès remarquable à la cour d'Henri III de France. Sa nature extravertie et son absence de muée (pelage hypoallergénique) en font un choix privilégié pour les allergiques.\n\nD'un naturel gai et affectueux, le Bichon s'adapte parfaitement à la vie en appartement et convient aux familles, aux personnes seules ou aux seniors. Son pelage bouclé nécessite cependant une toilette régulière pour éviter la formation de nœuds.",
    relatedArticleSlugs: ["allergie-chien-diagnostic", "toilettage-bichon-frise"],
    publishedAt: "2024-03-10",
    lastUpdatedAt: "2026-01-10",
  },
  {
    slug: "cavalier-king-charles",
    name: "Cavalier King Charles Spaniel",
    category: "chien",
    origin: "Angleterre",
    size: "petit",
    weightMale: { min: 5.9, max: 8.2 },
    weightFemale: { min: 5.9, max: 8.2 },
    heightMale: { min: 30, max: 33 },
    lifespanMin: 9,
    lifespanMax: 15,
    temperament: ["Affectueux", "Gentil", "Adaptatble", "Patient", "Sociable", "Joueur"],
    commonDiseases: [
      { name: "Insuffisance mitrale valvulaire (MVD)", prevalence: "frequente", description: "Maladie cardiaque valvulaire héréditaire — pratiquement universelle dans la race. À 10 ans, presque tous les Cavaliers en sont atteints à des degrés divers.", preventionTip: "Test cardiologique annuel (auscultation + échographie). Protocole d'élevage MVD strict. Traitement précoce (pimobendan stade B2)." },
      { name: "Syringomyélie / Malformation de Chiari", prevalence: "frequente", description: "Malformation crânienne entraînant des douleurs neuropathiques intenses (grattage de l'oreille, cris nocturnes). Liée à la morphologie brachycéphale de la race.", preventionTip: "Test IRM recommandé avant reproduction. Traitement médical (gabapentine, furosémide) ou chirurgical." },
      { name: "Épisodes de faiblesse brusque (EFS)", prevalence: "moderee", description: "Syndrome spécifique au Cavalier : effondrement lors de l'exercice ou des émotions, mimant une syncope cardiaque.", preventionTip: "Diagnostic d'exclusion après bilan cardiologique et neurologique. Éviter les déclencheurs (chaleur, excitation)." },
    ],
    careLevel: "modere",
    exerciseNeeds: "modere",
    groomingFrequency: "hebdomadaire",
    apartmentFriendly: true,
    goodWithChildren: true,
    goodWithOtherPets: true,
    recognizedBy: ["FCI", "LOF"],
    photo: "https://images.unsplash.com/photo-1612160742082-58be786fb1ec",
    description: "Le Cavalier King Charles Spaniel est l'un des chiens les plus affectueux et doux qui soit. Associé à la royauté britannique depuis le XVIIe siècle (le roi Charles II en était passionné), il a connu une renaissance au XXe siècle grâce au travail d'éleveurs américains soucieux de retrouver les formes de la race originelle.\n\nSa douceur exceptionnelle en fait un chien de thérapie idéal. Cependant, sa santé cardiaque est un sujet de préoccupation majeur : la maladie valvulaire mitrale est quasi-universelle dans la race après 10 ans. L'acquisition d'un Cavalier implique un suivi cardiologique rigoureux et des coûts vétérinaires potentiellement importants.",
    relatedArticleSlugs: ["insuffisance-cardiaque-chien-cavalier", "syringomyelie-cavalier-king-charles"],
    publishedAt: "2024-03-15",
    lastUpdatedAt: "2026-01-10",
  },
  {
    slug: "caniche",
    name: "Caniche",
    category: "chien",
    origin: "Allemagne / France",
    size: "moyen",
    weightMale: { min: 9, max: 19 },
    weightFemale: { min: 9, max: 19 },
    heightMale: { min: 35, max: 45 },
    lifespanMin: 12,
    lifespanMax: 15,
    temperament: ["Intelligent", "Actif", "Alert", "Entraînable", "Instinctif", "Fidèle"],
    commonDiseases: [
      { name: "Atrophie progressive de la rétine (APR)", prevalence: "frequente", description: "Dégénérescence progressive des photorécepteurs, conduisant à la cécité nocturne puis totale.", preventionTip: "Test génétique PRCD obligatoire pour les reproducteurs." },
      { name: "Maladie d'Addison", prevalence: "moderee", description: "Insuffisance surrénalienne (hypo-adrénocorticisme). Symptômes vagues : fatigue, vomissements épisodiques, effondrement lors de stress.", preventionTip: "Bilan hormonal (ACTH) si symptômes chroniques non spécifiques. Traitement à vie mais excellent pronostic." },
      { name: "Dermatite sébacée", prevalence: "moderee", description: "Inflammation des glandes sébacées entraînant une perte de poil et des squames.", preventionTip: "Diagnostic par biopsie cutanée. Traitement à base de bains et d'immunosuppresseurs." },
    ],
    careLevel: "modere",
    exerciseNeeds: "eleve",
    groomingFrequency: "mensuel",
    apartmentFriendly: true,
    goodWithChildren: true,
    goodWithOtherPets: true,
    recognizedBy: ["FCI", "LOF"],
    photo: "https://images.unsplash.com/photo-1561037404-61cd46aa615b",
    description: "Le Caniche est souvent cité comme l'une des races les plus intelligentes au monde, juste après le Border Collie. Contrairement aux idées reçues, c'est un chien de chasse et de rapport (notamment pour le gibier d'eau) avant d'être un chien d'agrément. Il existe en quatre tailles : grand, moyen, nain et toy.\n\nSon pelage bouclé et hypoallergénique (ne mue pratiquement pas) en fait un choix prisé des allergiques. Excellente mémoire, capacité d'apprentissage exceptionnelle et joie de vivre communicative : le Caniche est un compagnon idéal pour les familles actives. Sa toilette régulière est indispensable.",
    relatedArticleSlugs: ["maladie-addison-chien-symptomes"],
    publishedAt: "2024-03-20",
    lastUpdatedAt: "2026-01-10",
  },
  {
    slug: "beagle",
    name: "Beagle",
    category: "chien",
    origin: "Angleterre",
    size: "petit",
    weightMale: { min: 10, max: 11 },
    weightFemale: { min: 9, max: 10 },
    heightMale: { min: 33, max: 40 },
    lifespanMin: 12,
    lifespanMax: 15,
    temperament: ["Jovial", "Curieux", "Alert", "Amical", "Glouton", "Entêté"],
    commonDiseases: [
      { name: "Épilepsie", prevalence: "frequente", description: "Race surreprésentée pour l'épilepsie idiopathique. Première crise souvent entre 1 et 3 ans.", preventionTip: "Traitement antiépileptique (phénobarbital ou imépitoine) et suivi neurologique." },
      { name: "Hypothyroïdie", prevalence: "moderee", description: "Déficit en hormones thyroïdiennes. Se manifeste par une prise de poids, léthargie, troubles cutanés.", preventionTip: "Dosage TSH et T4 si symptômes. Traitement à la lévothyroxine à vie." },
      { name: "Glaucome", prevalence: "moderee", description: "Augmentation de la pression intraoculaire pouvant conduire à la cécité si non traitée.", preventionTip: "Mesure de la pression oculaire (tonomètre) lors des visites annuelles." },
    ],
    careLevel: "modere",
    exerciseNeeds: "eleve",
    groomingFrequency: "hebdomadaire",
    apartmentFriendly: false,
    goodWithChildren: true,
    goodWithOtherPets: true,
    recognizedBy: ["FCI", "LOF"],
    photo: "https://images.unsplash.com/photo-1505628346881-b72b27e84530",
    description: "Le Beagle est un chien courant de taille moyenne développé en Angleterre pour chasser le lièvre en meute. Son odorat extraordinaire (deuxième meilleur odorat après le Bloodhound) en a fait un outil précieux dans la détection de drogues et d'explosifs dans les aéroports.\n\nD'un naturel jovial et amical, le Beagle est excellent avec les enfants et d'autres chiens. Cependant, son instinct de chasse est très fort : une fois « sur une piste », il peut ignorer complètement son propriétaire. Son goût prononcé pour la nourriture le rend facile à motiver pour l'éducation mais prédisposé à l'obésité.",
    relatedArticleSlugs: ["epilepsie-chien-que-faire-crise"],
    publishedAt: "2024-04-01",
    lastUpdatedAt: "2026-01-10",
  },
  {
    slug: "dobermann",
    name: "Dobermann",
    category: "chien",
    origin: "Allemagne (Apolda, Thuringe)",
    size: "grand",
    weightMale: { min: 40, max: 45 },
    weightFemale: { min: 32, max: 35 },
    heightMale: { min: 68, max: 72 },
    lifespanMin: 10,
    lifespanMax: 13,
    temperament: ["Intelligent", "Énergique", "Loyal", "Alerte", "Courageux", "Obéissant"],
    commonDiseases: [
      { name: "Cardiomyopathie dilatée (DCM)", prevalence: "frequente", description: "Maladie cardiaque grave et souvent fatale dans la race. Jusqu'à 40% des Dobermanns développent une DCM occculte.", preventionTip: "Échocardiographie + holter cardiaque annuel dès 2 ans. Traitement précoce avec pimobendan si DCM occulte détectée." },
      { name: "Maladie de von Willebrand (vWD)", prevalence: "frequente", description: "Trouble de la coagulation par déficit en facteur de von Willebrand. Hémorragies prolongées lors de blessures ou de chirurgie.", preventionTip: "Test génétique vWD obligatoire avant toute intervention chirurgicale et pour les reproducteurs." },
      { name: "Hypothyroïdie", prevalence: "moderee", description: "Fréquente dans la race et souvent associée à des manifestations comportementales (agressivité, léthargie).", preventionTip: "Bilan thyroïdien si comportement ou métabolisme anormal." },
    ],
    careLevel: "exigeant",
    exerciseNeeds: "tres-eleve",
    groomingFrequency: "minimal",
    apartmentFriendly: false,
    goodWithChildren: true,
    goodWithOtherPets: true,
    recognizedBy: ["FCI", "LOF"],
    photo: "https://images.unsplash.com/photo-1613122656788-456da0b34e6f",
    description: "Le Dobermann a été créé dans les années 1880 par Karl Friedrich Louis Dobermann, percepteur d'impôts de la ville d'Apolda, qui souhaitait un chien de garde puissant pour l'accompagner dans ses tournées. Il a croisé diverses races (Rottweiler, Berger Allemand, Weimaraner, Greyhound) pour obtenir ce chien athlétique et intelligent.\n\nChien de travail par excellence, le Dobermann est utilisé dans la police et l'armée du monde entier. Mal socialisé, il peut être méfiant voire agressif. Bien éduqué, c'est un compagnon loyal et équilibré. La surveillance cardiaque est indispensable tout au long de sa vie.",
    relatedArticleSlugs: ["cardiomyopathie-dilatee-chien-dobermann"],
    publishedAt: "2024-04-05",
    lastUpdatedAt: "2026-01-10",
  },
  {
    slug: "boxer",
    name: "Boxer",
    category: "chien",
    origin: "Allemagne (Munich)",
    size: "grand",
    weightMale: { min: 27, max: 35 },
    weightFemale: { min: 24, max: 29 },
    heightMale: { min: 57, max: 63 },
    lifespanMin: 10,
    lifespanMax: 12,
    temperament: ["Loyal", "Affectueux", "Joueur", "Courageux", "Energique", "Protecteur"],
    commonDiseases: [
      { name: "Cardiomyopathie arythmogène du ventricule droit (CAVD)", prevalence: "frequente", description: "Maladie cardiaque génétique spécifique au Boxer. Arythmies ventriculaires pouvant causer mort subite.", preventionTip: "Holter cardiaque annuel dès 2 ans. Traitement antiarythmique si nécessaire." },
      { name: "Syndrome brachycéphale (BOAS)", prevalence: "moderee", description: "Obstruction respiratoire due au museau court.", preventionTip: "Éviter l'exercice par chaleur. Chirurgie corrective si sévère." },
      { name: "Tumeurs cutanées", prevalence: "frequente", description: "Le Boxer présente un risque élevé de tumeurs, notamment les mastocytomes et histiocytomes.", preventionTip: "Inspection mensuelle de la peau. Tout nodule nouveau doit être examiné par un vétérinaire." },
    ],
    careLevel: "modere",
    exerciseNeeds: "eleve",
    groomingFrequency: "minimal",
    apartmentFriendly: false,
    goodWithChildren: true,
    goodWithOtherPets: true,
    recognizedBy: ["FCI", "LOF"],
    photo: "https://images.unsplash.com/photo-1593134257782-e89567b7718a",
    description: "Le Boxer est issu de la sélection allemande de bullenbeissers (chiens mordeurs de taureaux) et de bulldogs anglais. Race de travail policier, il est aujourd'hui principalement un chien de famille apprécié pour son caractère enjoué et son dévouement. Son nom viendrait de son habitude de frapper avec ses pattes avant lors du jeu.\n\nExubérant et joueur jusqu'à un âge avancé, le Boxer est surnommé « le clown des grandes races ». Excellent avec les enfants, il est cependant à surveiller en raison de ses poussées d'enthousiasme et de sa force physique. Sa santé cardiaque nécessite un suivi spécialisé régulier.",
    relatedArticleSlugs: ["tumeurs-cutanees-chien-diagnostic"],
    publishedAt: "2024-04-10",
    lastUpdatedAt: "2026-01-10",
  },
  {
    slug: "malinois",
    name: "Berger Belge Malinois",
    category: "chien",
    origin: "Belgique (région de Malines)",
    size: "moyen",
    weightMale: { min: 25, max: 30 },
    weightFemale: { min: 20, max: 25 },
    heightMale: { min: 60, max: 66 },
    lifespanMin: 12,
    lifespanMax: 14,
    temperament: ["Très intelligent", "Intense", "Loyal", "Protecteur", "Alert", "Actif en permanence"],
    commonDiseases: [
      { name: "Dysplasie de la hanche", prevalence: "moderee", description: "Moins fréquente que dans les grandes races, mais présente dans la race.", preventionTip: "Tests des reproducteurs. Exercice contrôlé." },
      { name: "Épilepsie idiopathique", prevalence: "moderee", description: "Prédisposition héréditaire à l'épilepsie.", preventionTip: "Éviter les accouplements entre chiens affectés." },
    ],
    careLevel: "tres-exigeant",
    exerciseNeeds: "tres-eleve",
    groomingFrequency: "hebdomadaire",
    apartmentFriendly: false,
    goodWithChildren: false,
    goodWithOtherPets: false,
    recognizedBy: ["FCI", "LOF"],
    photo: "https://images.unsplash.com/photo-1553882809-a4f57e59501d",
    description: "Le Malinois est le chien de travail par excellence des forces de l'ordre et des armées mondiales. Utilisé par la CIA, les Navy SEALs et les polices du monde entier, il combine vitesse, intelligence, courage et une capacité de travail quasi-illimitée. Son intensité est incomparable parmi les races canines.\n\nCe n'est pas un chien pour novices. Le Malinois a besoin de plusieurs heures d'activité physique et mentale quotidienne. Sans cela, il peut devenir dangereux ou dévastateur. C'est un chien pour professionnels du travail canin ou sportifs de haut niveau souhaitant s'investir dans l'IPO, le RING ou le mordant.",
    relatedArticleSlugs: ["malinois-education-sport-canin"],
    publishedAt: "2024-04-15",
    lastUpdatedAt: "2026-01-10",
  },
  {
    slug: "cocker-anglais",
    name: "Cocker Spaniel Anglais",
    category: "chien",
    origin: "Angleterre",
    size: "petit",
    weightMale: { min: 12, max: 15 },
    weightFemale: { min: 10, max: 13 },
    heightMale: { min: 39, max: 41 },
    lifespanMin: 12,
    lifespanMax: 15,
    temperament: ["Joyeux", "Affectueux", "Actif", "Sociable", "Doux", "Joueur"],
    commonDiseases: [
      { name: "Otites chroniques", prevalence: "frequente", description: "Ses longues oreilles pendantes favorisent le manque de ventilation du conduit auditif, terrain idéal pour les infections récurrentes.", preventionTip: "Nettoyage hebdomadaire des oreilles avec un produit adapté. Séchage après chaque bain." },
      { name: "Cataracte héréditaire", prevalence: "frequente", description: "Opacification du cristallin d'origine génétique.", preventionTip: "Test génétique des reproducteurs. Suivi ophtalmologique annuel." },
      { name: "Syndrome de colère (Rage syndrome)", prevalence: "rare", description: "Épisodes soudains d'agressivité intense sans raison apparente, particulièrement rapportés chez les Cockers roux. Origine génétique suspectée.", preventionTip: "Sélection stricte des reproducteurs. Consultation comportementaliste si manifestation." },
    ],
    careLevel: "modere",
    exerciseNeeds: "eleve",
    groomingFrequency: "quotidien",
    apartmentFriendly: true,
    goodWithChildren: true,
    goodWithOtherPets: true,
    recognizedBy: ["FCI", "LOF"],
    photo: "https://images.unsplash.com/photo-1612535989696-4e7b5d69b2c3",
    description: "Le Cocker Spaniel Anglais est un chien de chasse et de compagnie d'une beauté remarquable, avec ses oreilles tombantes et sa robe soyeuse. Développé pour lever et rapporter le bécasseau (woodcock en anglais), d'où son nom, il est devenu l'un des chiens de compagnie les plus populaires d'Angleterre.\n\nD'un tempérament joyeux et affectueux, il est excellent en famille. Ses oreilles longues et son pelage abondant nécessitent un entretien régulier, notamment pour prévenir les otites chroniques, sa problématique de santé principale. Son pelage nécessite une toilette professionnelle tous les 2 à 3 mois.",
    relatedArticleSlugs: ["otite-chien-symptomes-traitement"],
    publishedAt: "2024-04-20",
    lastUpdatedAt: "2026-01-10",
  },
  {
    slug: "shih-tzu",
    name: "Shih Tzu",
    category: "chien",
    origin: "Chine (Tibet)",
    size: "petit",
    weightMale: { min: 4, max: 7 },
    weightFemale: { min: 4, max: 7 },
    heightMale: { min: 20, max: 28 },
    lifespanMin: 12,
    lifespanMax: 16,
    temperament: ["Affectueux", "Joueur", "Vif", "Loyal", "Arrogant (parfois)", "Doux"],
    commonDiseases: [
      { name: "Syndrome brachycéphale (BOAS)", prevalence: "moderee", description: "Obstruction respiratoire due au museau très court.", preventionTip: "Éviter l'exercice par chaleur. Chirurgie corrective si signes respiratoires." },
      { name: "Prolapsus de la glande de la membrane nictitante (Œil de cerise)", prevalence: "moderee", description: "Protrusion de la glande lacrymale de la troisième paupière, visible comme une masse rouge.", preventionTip: "Repositionnement chirurgical de la glande (ne pas exciser — risque de KCS)." },
      { name: "Luxation de la rotule", prevalence: "frequente", description: "Commune dans les petites races.", preventionTip: "Examen orthopédique annuel. Chirurgie si grade 3-4." },
    ],
    careLevel: "modere",
    exerciseNeeds: "faible",
    groomingFrequency: "quotidien",
    apartmentFriendly: true,
    goodWithChildren: true,
    goodWithOtherPets: true,
    recognizedBy: ["FCI", "LOF"],
    photo: "https://images.unsplash.com/photo-1526481280693-3bfa7568e0f3",
    description: "Le Shih Tzu (qui signifie « chien-lion » en chinois) est une race ancienne originaire du Tibet, offerte aux empereurs de Chine. Son pelage luxuriant et son apparence royale lui ont valu d'être un chien de palais apprécié des dynasties impériales chinoises.\n\nD'un caractère affectueux et joueur, le Shih Tzu convient parfaitement aux appartements et aux propriétaires peu sportifs. Son entretien quotidien est cependant conséquent — son pelage long peut être complexe à gérer. De nombreux propriétaires optent pour une coupe courte (« puppy cut ») pour faciliter l'entretien.",
    relatedArticleSlugs: ["syndrome-brachycephale-chien-traitement"],
    publishedAt: "2024-04-25",
    lastUpdatedAt: "2026-01-10",
  },
  {
    slug: "jack-russell-terrier",
    name: "Jack Russell Terrier",
    category: "chien",
    origin: "Angleterre (Devon)",
    size: "tres-petit",
    weightMale: { min: 6, max: 8 },
    weightFemale: { min: 5, max: 7 },
    heightMale: { min: 25, max: 30 },
    lifespanMin: 13,
    lifespanMax: 16,
    temperament: ["Vif", "Athétique", "Alert", "Courageux", "Énergique", "Têtu"],
    commonDiseases: [
      { name: "Ataxie cérébelleuse héréditaire (Spinocerebellar ataxia)", prevalence: "moderee", description: "Maladie neurologique progressive spécifique à la race. Test génétique disponible.", preventionTip: "Test génétique obligatoire pour les reproducteurs." },
      { name: "Surdité (liée au pelage blanc)", prevalence: "moderee", description: "Comme toutes les races à pelage majoritairement blanc, risque de surdité congénitale.", preventionTip: "Test BAER (réponse auditive du tronc cérébral) chez le chiot." },
      { name: "Luxation du cristallin", prevalence: "frequente", description: "Hérédité autosomal dominante dans la race. Luxation du cristallin pouvant causer glaucome et cécité.", preventionTip: "Test génétique PLL obligatoire pour les reproducteurs." },
    ],
    careLevel: "exigeant",
    exerciseNeeds: "tres-eleve",
    groomingFrequency: "hebdomadaire",
    apartmentFriendly: false,
    goodWithChildren: true,
    goodWithOtherPets: false,
    recognizedBy: ["FCI", "LOF"],
    photo: "https://images.unsplash.com/photo-1518020382113-a7e8fc38eac9",
    description: "Le Jack Russell Terrier a été développé au XIXe siècle par le Révérend John Russell pour chasser le renard. Petit mais redoutablement courageux et énergique, il était utilisé pour débusquer les renards et loutres de leur terrier pendant la chasse à courre.\n\nDerrière son air sympathique se cache un tempérament de terrier authentique : chasseur, têtu, explosif. Ce chien nécessite une éducation ferme et des activités quotidiennes intenses. Son instinct de prédation fort peut le rendre difficile avec les petits animaux. Un Jack Russell stimulé est un compagnon délicieux ; sous-stimulé, c'est un phénomène destructeur.",
    relatedArticleSlugs: ["jack-russell-education-bases"],
    publishedAt: "2024-05-01",
    lastUpdatedAt: "2026-01-10",
  },
  {
    slug: "epagneul-breton",
    name: "Épagneul Breton",
    category: "chien",
    origin: "France (Bretagne)",
    size: "moyen",
    weightMale: { min: 13, max: 18 },
    weightFemale: { min: 13, max: 18 },
    heightMale: { min: 47, max: 51 },
    lifespanMin: 12,
    lifespanMax: 14,
    temperament: ["Doux", "Intelligent", "Énergique", "Sociable", "Sensible", "Facile à éduquer"],
    commonDiseases: [
      { name: "Dysplasie de la hanche", prevalence: "moderee", description: "Moins fréquente que dans les grandes races mais présente.", preventionTip: "Tests des reproducteurs. Croissance modérée." },
      { name: "Épilepsie", prevalence: "moderee", description: "Prévalence légèrement supérieure à la moyenne des races.", preventionTip: "Éviter les croisements à risque." },
    ],
    careLevel: "modere",
    exerciseNeeds: "eleve",
    groomingFrequency: "hebdomadaire",
    apartmentFriendly: false,
    goodWithChildren: true,
    goodWithOtherPets: true,
    recognizedBy: ["FCI", "LOF"],
    photo: "https://images.unsplash.com/photo-1537151608828-ea2b11777ee8",
    description: "L'Épagneul Breton est la race française de chasse la plus populaire. Développé en Bretagne, il est le seul épagneul naturellement court de queue (ou sans queue). Excellent chien d'arrêt polyvalent, il brille sur tous types de terrains et de gibiers.\n\nD'un caractère doux, sensible et facile à éduquer, l'Épagneul Breton est également un remarquable chien de famille. Il s'adapte bien à la vie en milieu rural mais nécessite de longues balades quotidiennes. Son attachement à ses maîtres est fort — mal à l'aise s'il est isolé.",
    relatedArticleSlugs: [],
    publishedAt: "2024-05-05",
    lastUpdatedAt: "2026-01-10",
  },
  {
    slug: "spitz-nain",
    name: "Spitz Nain (Poméranien)",
    category: "chien",
    origin: "Région de Poméranie (Pologne / Allemagne)",
    size: "tres-petit",
    weightMale: { min: 1.8, max: 3.5 },
    weightFemale: { min: 1.8, max: 3.5 },
    heightMale: { min: 18, max: 22 },
    lifespanMin: 12,
    lifespanMax: 16,
    temperament: ["Vif", "Intelligent", "Curieux", "Sociable", "Joueur", "Parfois têtu"],
    commonDiseases: [
      { name: "Effondrement de la trachée", prevalence: "frequente", description: "Affaissement de la trachée causant une toux chronique. Commun dans les petites races.", preventionTip: "Harnais (pas de collier). Maintenir le poids idéal. Traitement médical." },
      { name: "Luxation de la rotule", prevalence: "frequente", description: "Très fréquente dans les petites races.", preventionTip: "Examen orthopédique annuel." },
      { name: "Alopécie X (syndrome de peau noire)", prevalence: "moderee", description: "Perte de poil progressive et hyperpigmentation, d'origine hormonale dans la race.", preventionTip: "Bilan hormonal complet. Stérilisation peut aider dans certains cas." },
    ],
    careLevel: "modere",
    exerciseNeeds: "modere",
    groomingFrequency: "quotidien",
    apartmentFriendly: true,
    goodWithChildren: true,
    goodWithOtherPets: true,
    recognizedBy: ["FCI", "LOF"],
    photo: "https://images.unsplash.com/photo-1601752881298-894bb81f9379",
    description: "Le Spitz Nain, connu aussi sous le nom de Poméranien, est issu des spitz de grande taille utilisés comme chiens de traîneaux en Poméranie. C'est la reine Victoria qui l'a popularisé en Grande-Bretagne en revenant de Florence avec un spitz dont elle s'était entiché.\n\nSon apparence de jouet — fourrure abondante en double couche, tête ronde, museau fin — cache un chien plein de vie et d'intelligence. Ses vocalises prononcées peuvent être problématiques en appartement. Son pelage nécessite un brossage quotidien pour éviter les nœuds.",
    relatedArticleSlugs: [],
    publishedAt: "2024-05-10",
    lastUpdatedAt: "2026-01-10",
  },
  {
    slug: "dalmatien",
    name: "Dalmatien",
    category: "chien",
    origin: "Croatie (région de Dalmatie)",
    size: "grand",
    weightMale: { min: 27, max: 32 },
    weightFemale: { min: 24, max: 28 },
    heightMale: { min: 56, max: 61 },
    lifespanMin: 11,
    lifespanMax: 13,
    temperament: ["Vif", "Actif", "Loyal", "Sensible", "Joueur", "Stable"],
    commonDiseases: [
      { name: "Surdité congénitale", prevalence: "frequente", description: "Liée au gène de la pigmentation (piébaldisme). Jusqu'à 8% des Dalmatiens sont sourds des deux oreilles, 22% d'une seule.", preventionTip: "Test BAER systématique des chiots avant vente. Éviter les accouplements entre deux chiens à yeux bleus (risque maximal)." },
      { name: "Urolithiase à urates", prevalence: "frequente", description: "Le Dalmatien a un métabolisme de l'acide urique différent des autres chiens — excrète de l'acide urique au lieu de l'allantoïne. Risque élevé de calculs urinaires.", preventionTip: "Alimentation pauvre en purines. Hydratation abondante. Acidification des urines. Contrôle urinaire annuel." },
    ],
    careLevel: "modere",
    exerciseNeeds: "tres-eleve",
    groomingFrequency: "hebdomadaire",
    apartmentFriendly: false,
    goodWithChildren: true,
    goodWithOtherPets: true,
    recognizedBy: ["FCI", "LOF"],
    photo: "https://images.unsplash.com/photo-1534361960057-19f4434a5d49",
    description: "Le Dalmatien est une race ancienne à la robe unique : fond blanc parsemé de taches noires ou marron parfaitement délimitées. Connu comme chien de carrosse au XVIIIe siècle et chien de pompier aux États-Unis (courant aux côtés des chevaux des brigades), il doit sa popularité mondiale au film de Disney.\n\nAthlète né, le Dalmatien nécessite plusieurs heures d'exercice quotidien pour être équilibré. Sa morphologie élancée et son endurance exceptionnelle le prédestinent au canicross ou au vélo accompagné. Ses problèmes de surdité et d'urolithiase nécessitent une vigilance particulière.",
    relatedArticleSlugs: [],
    publishedAt: "2024-05-15",
    lastUpdatedAt: "2026-01-10",
  },
  {
    slug: "saint-bernard",
    name: "Saint-Bernard",
    category: "chien",
    origin: "Suisse / Italie (hospice du Grand-Saint-Bernard)",
    size: "tres-grand",
    weightMale: { min: 64, max: 120 },
    weightFemale: { min: 54, max: 90 },
    heightMale: { min: 70, max: 90 },
    lifespanMin: 8,
    lifespanMax: 10,
    temperament: ["Doux", "Patient", "Bienveillant", "Loyal", "Calmement courageux"],
    commonDiseases: [
      { name: "Dysplasie de la hanche et du coude", prevalence: "frequente", description: "Sa masse corporelle colossale aggrave les contraintes articulaires. Chirurgies fréquentes.", preventionTip: "Tests radiographiques des reproducteurs. Croissance lente et contrôlée. Exercice adapté." },
      { name: "Dilatation-torsion de l'estomac", prevalence: "frequente", description: "Race à très haut risque de GDV en raison de sa poitrine profonde et de sa taille.", preventionTip: "Repas fractionnés. Repos post-repas 1h. Gastropexie préventive recommandée." },
      { name: "Ectropion", prevalence: "frequente", description: "Éversion de la paupière inférieure exposant la conjonctive. Prédisposition liée au standard racial.", preventionTip: "Nettoyage oculaire régulier. Chirurgie si irritation chronique." },
    ],
    careLevel: "modere",
    exerciseNeeds: "modere",
    groomingFrequency: "hebdomadaire",
    apartmentFriendly: false,
    goodWithChildren: true,
    goodWithOtherPets: true,
    recognizedBy: ["FCI", "LOF"],
    photo: "https://images.unsplash.com/photo-1633722715463-d30628ceb4f9",
    description: "Le Saint-Bernard est le géant bienveillant des races canines, rendu célèbre pour ses sauvetages dans les cols alpins depuis le XVIIe siècle. Les moines de l'Hospice du Grand-Saint-Bernard en Suisse ont développé cette race pour retrouver les voyageurs perdus dans la neige — la légende du tonnelet de rhum est cependant apocryphe.\n\nD'une douceur et d'une patience remarquables, le Saint-Bernard est excellent avec les enfants. Sa taille imposante nécessite une éducation précoce solide — un chien de 90 kg non éduqué est incontrôlable. Sa durée de vie limitée (8-10 ans) est la rançon de son gabarit exceptionnel.",
    relatedArticleSlugs: ["dilation-torsion-estomac-urgence"],
    publishedAt: "2024-05-20",
    lastUpdatedAt: "2026-01-10",
  },

  // ══ CHATS ══════════════════════════════════════════════════════════════════

  {
    slug: "maine-coon",
    name: "Maine Coon",
    category: "chat",
    origin: "États-Unis (état du Maine)",
    size: "grand",
    weightMale: { min: 6, max: 10 },
    weightFemale: { min: 4, max: 7 },
    lifespanMin: 12,
    lifespanMax: 15,
    temperament: ["Doux géant", "Sociable", "Joueur", "Intelligent", "Adaptable", "Dog-like"],
    commonDiseases: [
      { name: "Cardiomyopathie hypertrophique (CMH)", prevalence: "frequente", description: "Maladie cardiaque héréditaire — épaississement du muscle cardiaque. Mutation MYBPC3 fréquente chez le Maine Coon.", preventionTip: "Échocardiographie annuelle dès 2 ans. Test génétique MYBPC3 des reproducteurs." },
      { name: "Dysplasie de la hanche", prevalence: "moderee", description: "Malformation articulaire possible dans cette grande race féline.", preventionTip: "Radiographies des reproducteurs. Éviter surpoids." },
      { name: "Polykystose rénale (PKD)", prevalence: "moderee", description: "Formation de kystes dans les reins, conduisant à une insuffisance rénale progressive.", preventionTip: "Test génétique PKD des reproducteurs. Échographie rénale annuelle." },
    ],
    careLevel: "modere",
    exerciseNeeds: "modere",
    groomingFrequency: "hebdomadaire",
    apartmentFriendly: true,
    goodWithChildren: true,
    goodWithOtherPets: true,
    recognizedBy: ["LOOF", "FCI", "TICA", "CFA"],
    photo: "https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13",
    description: "Le Maine Coon est la plus grande race de chat domestique reconnue. Originaire de l'état du Maine aux États-Unis, il est souvent surnommé « le chien du monde des chats » en raison de son caractère sociable et joueur, même avec des inconnus. Sa robe mi-longue avec collerette et son queue en panache sont caractéristiques.\n\nExtrêmement adaptable, il s'entend bien avec les enfants, les chiens et autres chats. Curieux et intelligent, il peut apprendre à rapporter des jouets. Sa santé cardiaque doit être surveillée régulièrement — la cardiomyopathie hypertrophique est héréditaire dans la race.",
    relatedArticleSlugs: ["cardiomyopathie-hypertrophique-chat", "maine-coon-soins"],
    publishedAt: "2024-01-25",
    lastUpdatedAt: "2026-01-10",
  },
  {
    slug: "ragdoll",
    name: "Ragdoll",
    category: "chat",
    origin: "États-Unis (Californie)",
    size: "grand",
    weightMale: { min: 6, max: 9 },
    weightFemale: { min: 4, max: 6 },
    lifespanMin: 12,
    lifespanMax: 17,
    temperament: ["Doux", "Calm", "Sociable", "Affectueux", "Placide", "Peu vocaux"],
    commonDiseases: [
      { name: "Cardiomyopathie hypertrophique (CMH)", prevalence: "frequente", description: "Comme le Maine Coon, le Ragdoll est surreprésenté pour la CMH. Mutation MYBPC3 spécifique à la race.", preventionTip: "Échocardiographie annuelle. Test génétique obligatoire des reproducteurs." },
      { name: "Polykystose rénale (PKD)", prevalence: "moderee", description: "Formation de kystes rénaux héréditaires.", preventionTip: "Test génétique PKD1 des reproducteurs." },
      { name: "Tendance à l'obésité", prevalence: "moderee", description: "Sa nature passive et son manque d'initiative à l'exercice favorisent la prise de poids.", preventionTip: "Peser régulièrement. Alimentation mesurée. Jeux interactifs pour stimuler l'activité." },
    ],
    careLevel: "facile",
    exerciseNeeds: "faible",
    groomingFrequency: "hebdomadaire",
    apartmentFriendly: true,
    goodWithChildren: true,
    goodWithOtherPets: true,
    recognizedBy: ["LOOF", "TICA", "CFA"],
    photo: "https://images.unsplash.com/photo-1561948955-570b270e7c36",
    description: "Le Ragdoll doit son nom à sa caractéristique de se détendre comme une poupée de chiffon (ragdoll en anglais) quand on le prend dans les bras. Créé dans les années 1960 en Californie par Ann Baker, il est rapidement devenu l'une des races les plus populaires au monde pour son tempérament exceptionnel.\n\nIdéal pour les appartements et les familles, le Ragdoll est un chat doux, peu turbulent et peu vocaux. Son pelage semi-long nécessite un brossage hebdomadaire. Sa passivité peut le mettre en danger (mauvaise réactivité aux agressions extérieures) — la vie en intérieur est recommandée.",
    relatedArticleSlugs: ["cardiomyopathie-hypertrophique-chat"],
    publishedAt: "2024-02-01",
    lastUpdatedAt: "2026-01-10",
  },
  {
    slug: "british-shorthair",
    name: "British Shorthair",
    category: "chat",
    origin: "Grande-Bretagne",
    size: "grand",
    weightMale: { min: 5, max: 8 },
    weightFemale: { min: 3.5, max: 5.5 },
    lifespanMin: 14,
    lifespanMax: 20,
    temperament: ["Calme", "Affectueux sans être collant", "Discret", "Patient", "Indépendant", "Loyal"],
    commonDiseases: [
      { name: "Cardiomyopathie hypertrophique (CMH)", prevalence: "frequente", description: "Surreprésentée dans la race. Dépistage régulier indispensable.", preventionTip: "Échocardiographie annuelle." },
      { name: "Polykystose rénale (PKD)", prevalence: "moderee", description: "Kystes rénaux héréditaires. Test génétique disponible.", preventionTip: "Test PKD1 pour les reproducteurs." },
      { name: "Obésité", prevalence: "frequente", description: "Sa nature sédentaire le prédispose à la prise de poids, favorisant le diabète et les arthrites.", preventionTip: "Alimentation mesurée, jeux quotidiens, pesée mensuelle." },
    ],
    careLevel: "facile",
    exerciseNeeds: "faible",
    groomingFrequency: "hebdomadaire",
    apartmentFriendly: true,
    goodWithChildren: true,
    goodWithOtherPets: true,
    recognizedBy: ["LOOF", "TICA", "CFA"],
    photo: "https://images.unsplash.com/photo-1573865526739-10659fec78a5",
    description: "Le British Shorthair est probablement descendant des chats domestiques amenés en Grande-Bretagne par les Romains. Sa morphologie massive et son pelage dense en font le chat le plus robuste des races européennes. Le chat d'Alice au Pays des Merveilles (le Chat du Cheshire) est souvent représenté comme un British Shorthair.\n\nDisposant d'un tempérament équilibré et d'une grande adaptabilité, le British Shorthair convient à tous les foyers. Affectueux sans être envahissant, il accepte bien la solitude modérée. Sa longévité remarquable (jusqu'à 20 ans) en fait un compagnon de vie précieux.",
    relatedArticleSlugs: ["obésite-chat-consequences-traitement"],
    publishedAt: "2024-02-05",
    lastUpdatedAt: "2026-01-10",
  },
  {
    slug: "persan",
    name: "Persan",
    category: "chat",
    origin: "Perse (actuel Iran)",
    size: "moyen",
    weightMale: { min: 4, max: 6 },
    weightFemale: { min: 3, max: 5 },
    lifespanMin: 12,
    lifespanMax: 17,
    temperament: ["Calme", "Doux", "Affectueux", "Discret", "Peu actif", "Attached à son foyer"],
    commonDiseases: [
      { name: "Polykystose rénale (PKD)", prevalence: "frequente", description: "Jusqu'à 40% des Persans sont porteurs de la mutation PKD1. Conduit à une insuffisance rénale progressive.", preventionTip: "Test génétique PKD1 obligatoire des reproducteurs. Suivi rénal annuel." },
      { name: "Syndrome brachycéphale occulaire", prevalence: "frequente", description: "Morphologie aplatie entraînant des troubles oculaires (épiphora, ulcères cornéens) et respiratoires.", preventionTip: "Nettoyage quotidien des yeux. Suivi ophtalmologique annuel. Chirurgie corrective si nécessaire." },
      { name: "Cardiomyopathie hypertrophique (CMH)", prevalence: "moderee", description: "Épaississement du muscle cardiaque héréditaire.", preventionTip: "Échocardiographie annuelle dès 5 ans." },
    ],
    careLevel: "exigeant",
    exerciseNeeds: "faible",
    groomingFrequency: "quotidien",
    apartmentFriendly: true,
    goodWithChildren: true,
    goodWithOtherPets: true,
    recognizedBy: ["LOOF", "FCI", "TICA", "CFA"],
    photo: "https://images.unsplash.com/photo-1595433562696-2e23e2b4b2a2",
    description: "Le Persan est l'une des races les plus anciennes et les plus populaires du monde. Apporté en Europe depuis la Perse au XVIIe siècle, il a connu une sélection intensive qui a accentué sa morphologie brachycéphale (aplatie) et son pelage luxuriant. Il existe en deux variétés : traditionnelle (muffle pas totalement aplati) et extrême (show type).\n\nChoisir un Persan implique de s'engager dans un entretien quotidien intensif de son pelage long (brossage, dénouer les nœuds) et le nettoyage de ses yeux (larmoiement chronique). Sa santé rénale doit être surveillée via un test génétique et un suivi annuel.",
    relatedArticleSlugs: ["polykystose-renale-chat-pkd", "toilettage-persan"],
    publishedAt: "2024-02-10",
    lastUpdatedAt: "2026-01-10",
  },
  {
    slug: "bengal",
    name: "Bengal",
    category: "chat",
    origin: "États-Unis (croisement chat domestique × chat-léopard asiatique)",
    size: "moyen",
    weightMale: { min: 4.5, max: 7 },
    weightFemale: { min: 3.5, max: 5 },
    lifespanMin: 12,
    lifespanMax: 16,
    temperament: ["Actif", "Curieux", "Joueur", "Intelligent", "Athletique", "Sociable"],
    commonDiseases: [
      { name: "Leucodystrophie (PRA-b)", prevalence: "moderee", description: "Atrophie progressive de la rétine spécifique au Bengal, conduisant à la cécité nocturne.", preventionTip: "Test génétique PRA-b des reproducteurs." },
      { name: "Cardiomyopathie hypertrophique (CMH)", prevalence: "moderee", description: "Moins fréquente que dans d'autres races mais présente.", preventionTip: "Échocardiographie annuelle dès 2 ans." },
      { name: "Tritrichomonose", prevalence: "moderee", description: "Infection intestinale par Tritrichomonas foetus, causant des diarrhées chroniques. Fréquent dans les chatteries.", preventionTip: "Tests fécaux réguliers. Traitement au ronidazole sur prescription." },
    ],
    careLevel: "exigeant",
    exerciseNeeds: "tres-eleve",
    groomingFrequency: "minimal",
    apartmentFriendly: false,
    goodWithChildren: true,
    goodWithOtherPets: true,
    recognizedBy: ["LOOF", "TICA"],
    photo: "https://images.unsplash.com/photo-1535930749574-1399327ce78f",
    description: "Le Bengal est issu du croisement entre un chat domestique et un chat-léopard asiatique (Prionailurus bengalensis). Sa robe tachetée ou marbrée, qui rappelle celle d'un léopard, est sa caractéristique la plus frappante. Il n'a été reconnu comme race domestique qu'à partir de la 4e génération (F4) après le croisement avec le chat sauvage.\n\nExtrêmement actif et curieux, le Bengal n'est pas adapté à la vie sédentaire en appartement sans stimulation importante. Il aime grimper, chasser et même parfois jouer avec l'eau. Ses propriétaires doivent prévoir des structures de jeu importantes (arbres à chats, tunnels) et des sessions de jeu interactif quotidiennes.",
    relatedArticleSlugs: ["chat-sauvage-domestic-hybrides"],
    publishedAt: "2024-02-15",
    lastUpdatedAt: "2026-01-10",
  },
  {
    slug: "siamois",
    name: "Siamois",
    category: "chat",
    origin: "Thaïlande (ancienne Siam)",
    size: "moyen",
    weightMale: { min: 4, max: 6 },
    weightFemale: { min: 3, max: 5 },
    lifespanMin: 12,
    lifespanMax: 20,
    temperament: ["Vocal", "Curieux", "Sociable", "Affectueux", "Intelligent", "Exigeant"],
    commonDiseases: [
      { name: "Amyloïdose hépatique", prevalence: "moderee", description: "Dépôt d'amyloïde dans le foie, spécifique aux races orientales. Peut causer insuffisance hépatique et hémorragies.", preventionTip: "Bilan hépatique annuel dès 7 ans. Traitement symptomatique." },
      { name: "Mégacôlon", prevalence: "moderee", description: "Constipation chronique sévère avec dilatation colique. Surreprésentée chez le Siamois.", preventionTip: "Alimentation riche en eau (pâtée), lactulose si besoin, suivi digestif." },
      { name: "Strabisme convergent", prevalence: "frequente", description: "Déviation des yeux vers l'intérieur. Liée à la génétique de la race. Généralement bénigne.", preventionTip: "Aucune intervention nécessaire en général — défaut esthétique uniquement." },
    ],
    careLevel: "modere",
    exerciseNeeds: "eleve",
    groomingFrequency: "minimal",
    apartmentFriendly: true,
    goodWithChildren: true,
    goodWithOtherPets: true,
    recognizedBy: ["LOOF", "TICA", "CFA"],
    photo: "https://images.unsplash.com/photo-1545249390-6bdfa286032f",
    description: "Le Siamois est l'une des races félines les plus anciennes et les plus reconnaissables au monde. Originaire de Thaïlande (l'ancien Siam), il était considéré comme sacré et vivait dans les temples bouddhistes. Sa robe colorpoint (pattes, queue, masque et oreilles foncés sur fond crème) et ses yeux bleus intenses sont caractéristiques.\n\nPersonnalité remarquable : le Siamois est un chat extrêmement bavard (miaulement proche de celui d'un bébé humain), curieux et exigeant. Il ne supporte pas la solitude prolongée et demande une présence humaine importante. Excellent avec les enfants, c'est un chat de compagnie très engageant.",
    relatedArticleSlugs: ["chat-vocal-miaulements-causes"],
    publishedAt: "2024-02-20",
    lastUpdatedAt: "2026-01-10",
  },
  {
    slug: "sacre-de-birmanie",
    name: "Sacré de Birmanie",
    category: "chat",
    origin: "France (sélection à partir de races orientales)",
    size: "moyen",
    weightMale: { min: 4.5, max: 7 },
    weightFemale: { min: 3.5, max: 6 },
    lifespanMin: 12,
    lifespanMax: 16,
    temperament: ["Doux", "Sociable", "Calme", "Joueur", "Loyal", "Peu vocal"],
    commonDiseases: [
      { name: "Cardiomyopathie hypertrophique (CMH)", prevalence: "frequente", description: "Prévalente dans la race. Suivi cardiologique indispensable.", preventionTip: "Échocardiographie annuelle." },
      { name: "Troubles de la kératinisation", prevalence: "moderee", description: "Problèmes de peau et de pelage liés à des troubles de la kératinisation seborrheique.", preventionTip: "Bains médicamenteux. Consultation dermatologique vétérinaire." },
    ],
    careLevel: "modere",
    exerciseNeeds: "modere",
    groomingFrequency: "hebdomadaire",
    apartmentFriendly: true,
    goodWithChildren: true,
    goodWithOtherPets: true,
    recognizedBy: ["LOOF", "FCI", "TICA"],
    photo: "https://images.unsplash.com/photo-1516750105099-4b8a83e217ee",
    description: "Le Sacré de Birmanie (à ne pas confondre avec le Birman) est une race développée en France dans les années 1920 à partir de chats orientaux ramenés de Birmanie. Sa caractéristique la plus distinctive est son pelage colorpoint avec des gants blancs sur les quatre pattes — une marque de fabrique unique.\n\nD'un caractère équilibré et sociable, le Birman s'adapte bien à la vie en appartement et cohabite harmonieusement avec les enfants et d'autres animaux. Son pelage semi-long, bien que moins dense que celui du Persan, nécessite un brossage hebdomadaire régulier.",
    relatedArticleSlugs: [],
    publishedAt: "2024-03-01",
    lastUpdatedAt: "2026-01-10",
  },
  {
    slug: "sphynx",
    name: "Sphynx",
    category: "chat",
    origin: "Canada (Ontario, 1966)",
    size: "moyen",
    weightMale: { min: 4, max: 6 },
    weightFemale: { min: 3, max: 5 },
    lifespanMin: 12,
    lifespanMax: 15,
    temperament: ["Très affectueux", "Chaleureux", "Sociable", "Joueur", "Curieux", "Collant"],
    commonDiseases: [
      { name: "Cardiomyopathie hypertrophique (CMH)", prevalence: "frequente", description: "Très forte prévalence dans la race. Jusqu'à 33% des Sphynx sont affectés.", preventionTip: "Échocardiographie annuelle dès 1 an. Test génétique si disponible." },
      { name: "Myopathie du Sphynx", prevalence: "moderee", description: "Dystrophie musculaire héréditaire spécifique à la race.", preventionTip: "Observation du comportement musculaire. Consultation neurologique si signes." },
      { name: "Problèmes cutanés", prevalence: "frequente", description: "Accumulation de sébum sur la peau chaude et sans poils, favorisant les infections.", preventionTip: "Bains hebdomadaires avec shampoing doux. Nettoyage des plis et des oreilles." },
    ],
    careLevel: "exigeant",
    exerciseNeeds: "eleve",
    groomingFrequency: "hebdomadaire",
    apartmentFriendly: true,
    goodWithChildren: true,
    goodWithOtherPets: true,
    recognizedBy: ["LOOF", "TICA", "CFA"],
    photo: "https://images.unsplash.com/photo-1596853341798-95a88b6d70b8",
    description: "Le Sphynx est né d'une mutation spontanée du gène codant pour le poil, apparue pour la première fois à Toronto en 1966. Contrairement à une idée reçue, ce n'est pas un chat hypoallergénique — l'allergène principal (Fel d 1) est dans la salive et les glandes sébacées, pas dans le poil.\n\nExtrêmement tactile et collant, le Sphynx cherche en permanence la chaleur corporelle humaine. Il ne supporte pas le froid et ne peut pas vivre à l'extérieur. Sa peau nécessite un entretien hebdomadaire (bain) pour éliminer le sébum qui s'accumule. Sa santé cardiaque doit être surveillée très rigoureusement.",
    relatedArticleSlugs: ["cardiomyopathie-hypertrophique-chat", "allergie-chat-solutions"],
    publishedAt: "2024-03-05",
    lastUpdatedAt: "2026-01-10",
  },
  {
    slug: "chat-norvegien",
    name: "Chat des Forêts Norvégiennes",
    category: "chat",
    origin: "Norvège",
    size: "grand",
    weightMale: { min: 5, max: 8 },
    weightFemale: { min: 4, max: 6 },
    lifespanMin: 12,
    lifespanMax: 16,
    temperament: ["Indépendant", "Affectueux (à ses heures)", "Joueur", "Alert", "Adaptable", "Robuste"],
    commonDiseases: [
      { name: "Glycogénose type IV (GSD IV)", prevalence: "rare", description: "Maladie de stockage du glycogène, mortelle pour les chatons affectés. Test génétique disponible.", preventionTip: "Test génétique obligatoire pour les reproducteurs." },
      { name: "Cardiomyopathie hypertrophique (CMH)", prevalence: "moderee", description: "Comme toutes les grandes races, prévalence non négligeable.", preventionTip: "Échocardiographie annuelle." },
    ],
    careLevel: "modere",
    exerciseNeeds: "eleve",
    groomingFrequency: "hebdomadaire",
    apartmentFriendly: true,
    goodWithChildren: true,
    goodWithOtherPets: true,
    recognizedBy: ["LOOF", "FCI", "TICA"],
    photo: "https://images.unsplash.com/photo-1598439210625-5067c578f3f6",
    description: "Le Chat des Forêts Norvégiennes (Norsk Skogkatt en norvégien) est une race nordique ancienne, mentionnée dans les mythes vikings. Son double pelage imperméable, ses touffes de poils entre les doigts et sa musculature puissante témoignent d'une adaptation parfaite aux rudes hivers scandinaves.\n\nAthlétique et curieux, il aime explorer et grimper. Sa nature semi-indépendante le rend moins collant que d'autres races, mais il est affectueux avec sa famille. Son pelage nécessite un entretien hebdomadaire, surtout lors des mues saisonnières (printemps, automne).",
    relatedArticleSlugs: [],
    publishedAt: "2024-03-10",
    lastUpdatedAt: "2026-01-10",
  },
  {
    slug: "abyssin",
    name: "Abyssin",
    category: "chat",
    origin: "Ethiopie (ancienne Abyssinie) / Angleterre",
    size: "moyen",
    weightMale: { min: 4, max: 5.5 },
    weightFemale: { min: 3, max: 4.5 },
    lifespanMin: 12,
    lifespanMax: 15,
    temperament: ["Très actif", "Curieux", "Joueur", "Intelligent", "Sociable", "Non collant"],
    commonDiseases: [
      { name: "Amyloïdose rénale", prevalence: "frequente", description: "Dépôt d'amyloïde dans les reins, spécifique à la race. Conduit à une insuffisance rénale progressive, souvent à partir de 3-5 ans.", preventionTip: "Bilan rénal annuel (urée, créatinine, SDMA). Pas de traitement curatif — soins palliatifs." },
      { name: "Atrophie progressive de la rétine (PRA-rdAc)", prevalence: "moderee", description: "Dégénérescence rétinienne héréditaire. Test génétique disponible.", preventionTip: "Test génétique rdAc pour les reproducteurs." },
    ],
    careLevel: "modere",
    exerciseNeeds: "tres-eleve",
    groomingFrequency: "minimal",
    apartmentFriendly: false,
    goodWithChildren: true,
    goodWithOtherPets: true,
    recognizedBy: ["LOOF", "TICA", "CFA"],
    photo: "https://images.unsplash.com/photo-1511044568932-338ceba04967",
    description: "L'Abyssin est souvent surnommé « le singe des chats » en raison de son insatiable curiosité et de son goût pour l'escalade. Sa robe tiquetée (chaque poil a plusieurs bandes de couleur) lui donne l'apparence d'un chat sauvage. On le rapproche souvent du chat de l'Egypte ancienne.\n\nExtrêmement actif et agile, l'Abyssin n'est pas adapté à la vie sédentaire. Il doit pouvoir grimper, explorer et jouer. Sa nature peu collante (il observe plutôt qu'il ne câline) peut décevoir les propriétaires cherchant un chat très affectueux. Sa santé rénale doit être surveillée régulièrement.",
    relatedArticleSlugs: ["amyloidose-renale-chat-abyssin"],
    publishedAt: "2024-03-15",
    lastUpdatedAt: "2026-01-10",
  },
  {
    slug: "scottish-fold",
    name: "Scottish Fold",
    category: "chat",
    origin: "Écosse",
    size: "moyen",
    weightMale: { min: 4, max: 6 },
    weightFemale: { min: 3, max: 5 },
    lifespanMin: 11,
    lifespanMax: 15,
    temperament: ["Calme", "Doux", "Adaptable", "Joueur", "Sociable", "Loyal"],
    commonDiseases: [
      { name: "Ostéochond rodysplasie (OCD)", prevalence: "frequente", description: "La mutation Fd (oreilles pliées) est une mutation du cartilage affectant TOUT le squelette. Les Scottish Fold homozygotes (deux copies) développent une arthrite sévère et douloureuse des membres et de la queue.", preventionTip: "Ne JAMAIS accoupler deux Scottish Fold ensemble (risque de chitons homozygotes sévèrement affectés). Préférer les Scottish Straight (oreilles droites). Radiographies si douleur suspectée." },
      { name: "Cardiomyopathie hypertrophique (CMH)", prevalence: "moderee", description: "Fréquente dans la race. Suivi cardiologique obligatoire.", preventionTip: "Échocardiographie annuelle." },
    ],
    careLevel: "modere",
    exerciseNeeds: "modere",
    groomingFrequency: "hebdomadaire",
    apartmentFriendly: true,
    goodWithChildren: true,
    goodWithOtherPets: true,
    recognizedBy: ["TICA", "CFA"],
    photo: "https://images.unsplash.com/photo-1596854407944-bf87f6fdd49e",
    description: "Le Scottish Fold doit son nom à ses oreilles repliées vers l'avant, dues à une mutation cartillagineuse découverte en 1961 en Écosse. Sa physionomie avec ses grands yeux ronds et ses petites oreilles plates lui donne une apparence de chouette très appréciée.\n\nCependant, la mutation responsable des oreilles pliées (gène Fd) est une mutation du cartilage qui affecte l'ensemble du squelette, provoquant douleurs chroniques et arthrite progressive. De nombreux pays d'Europe interdisent désormais l'élevage des Scottish Fold en raison de ces problèmes de bien-être animal. Un animal adopté doit bénéficier d'un suivi vétérinaire attentif.",
    relatedArticleSlugs: ["scottish-fold-bien-etre-controverse"],
    publishedAt: "2024-03-20",
    lastUpdatedAt: "2026-01-10",
  },
  {
    slug: "chartreux",
    name: "Chartreux",
    category: "chat",
    origin: "France",
    size: "moyen",
    weightMale: { min: 4.5, max: 7 },
    weightFemale: { min: 3.5, max: 5.5 },
    lifespanMin: 12,
    lifespanMax: 15,
    temperament: ["Calme", "Doux", "Discret", "Loyal", "Tranquille", "Peu vocal"],
    commonDiseases: [
      { name: "Luxation de la rotule", prevalence: "moderee", description: "La race est prédisposée à la luxation de la rotule en raison de sa morphologie.", preventionTip: "Examen orthopédique annuel." },
      { name: "Polykystose rénale (PKD)", prevalence: "moderee", description: "Présente dans la race bien que moins qu'en Persan.", preventionTip: "Test génétique des reproducteurs." },
    ],
    careLevel: "facile",
    exerciseNeeds: "modere",
    groomingFrequency: "hebdomadaire",
    apartmentFriendly: true,
    goodWithChildren: true,
    goodWithOtherPets: true,
    recognizedBy: ["LOOF", "FCI", "TICA"],
    photo: "https://images.unsplash.com/photo-1494256997604-768d1f608cac",
    description: "Le Chartreux est l'une des rares races félines véritablement françaises. Sa robe bleue unique (toutes nuances de gris-bleu), ses yeux orange ou cuivrés et son sourire légèrement retroussé sont caractéristiques. La légende veut que les moines chartreux de la Grande Chartreuse l'auraient élevé au Moyen-Âge.\n\nD'un tempérament remarquablement équilibré, le Chartreux est un chat discret, peu vocal, qui s'adapte parfaitement à toutes les situations. Affectueux avec sa famille sans être envahissant, il est peu exigeant et convient aux propriétaires moins disponibles. Sa nature robuste en fait généralement un chat en bonne santé.",
    relatedArticleSlugs: [],
    publishedAt: "2024-03-25",
    lastUpdatedAt: "2026-01-10",
  },
  {
    slug: "devon-rex",
    name: "Devon Rex",
    category: "chat",
    origin: "Angleterre (Devon)",
    size: "petit",
    weightMale: { min: 3, max: 4.5 },
    weightFemale: { min: 2.5, max: 4 },
    lifespanMin: 12,
    lifespanMax: 15,
    temperament: ["Espiègle", "Sociable", "Joueur", "Affectueux", "Collant", "Dès fois malicieux"],
    commonDiseases: [
      { name: "Myopathie héréditaire du Devon Rex", prevalence: "frequente", description: "Dystrophie musculaire spécifique à la race. Faiblesse musculaire progressive, notamment de la tête et du cou (tête qui tombe lors de l'effort).", preventionTip: "Test génétique obligatoire pour les reproducteurs. Pas de traitement curatif." },
      { name: "Malassezia (infections cutanées)", prevalence: "moderee", description: "Propension aux infections à Malassezia sur la peau et les oreilles en raison de la structure particulière de son pelage.", preventionTip: "Bains réguliers au shampoing antifongique. Nettoyage des oreilles." },
    ],
    careLevel: "modere",
    exerciseNeeds: "eleve",
    groomingFrequency: "hebdomadaire",
    apartmentFriendly: true,
    goodWithChildren: true,
    goodWithOtherPets: true,
    recognizedBy: ["LOOF", "TICA", "CFA"],
    photo: "https://images.unsplash.com/photo-1603803397753-d7c5dc98ed51",
    description: "Le Devon Rex est né d'une mutation spontanée en 1960 dans le Devon, en Angleterre. Son pelage court, ondulé et fragile (les poils se cassent facilement), ses grandes oreilles et ses yeux immenses lui donnent un air de pixie ou d'elfe. Chaque Devon Rex a un motif de pelage unique.\n\nPersonnalité extravertie et espiègle, le Devon Rex est souvent décrit comme un chien dans un corps de chat. Il suit ses propriétaires partout, adore les épaules et les têtes comme perchoir, et joue jusqu'à l'épuisement. Parfait pour les familles actives cherchant un chat très interactif.",
    relatedArticleSlugs: [],
    publishedAt: "2024-03-30",
    lastUpdatedAt: "2026-01-10",
  },
];

// ── Utility functions ──────────────────────────────────────────────────────

export function getBreed(slug: string): BreedProfile | undefined {
  return BREEDS.find((b) => b.slug === slug);
}

export function getAllBreeds(): BreedProfile[] {
  return BREEDS;
}

export function getBreedsByCategory(category: BreedCategory): BreedProfile[] {
  return BREEDS.filter((b) => b.category === category);
}

export function getAllBreedSlugs(): string[] {
  return BREEDS.map((b) => b.slug);
}

export const SIZE_LABELS: Record<BreedSize, string> = {
  "tres-petit": "Très petit (< 5 kg)",
  "petit": "Petit (5–15 kg)",
  "moyen": "Moyen (15–30 kg)",
  "grand": "Grand (30–50 kg)",
  "tres-grand": "Très grand (> 50 kg)",
};

export const CARE_LEVEL_LABELS: Record<CareLevel, string> = {
  "facile": "Facile",
  "modere": "Modéré",
  "exigeant": "Exigeant",
  "tres-exigeant": "Très exigeant",
};

export const EXERCISE_LABELS: Record<ExerciseNeeds, string> = {
  "faible": "Faible",
  "modere": "Modéré",
  "eleve": "Élevé",
  "tres-eleve": "Très élevé",
};

export const GROOMING_LABELS: Record<GroomingFrequency, string> = {
  "minimal": "Minimal (mensuel ou moins)",
  "mensuel": "Mensuel",
  "hebdomadaire": "Hebdomadaire",
  "quotidien": "Quotidien",
};

export const PREVALENCE_LABELS: Record<Prevalence, string> = {
  "frequente": "Fréquente",
  "moderee": "Modérée",
  "rare": "Rare",
};

export const PREVALENCE_COLORS: Record<Prevalence, string> = {
  "frequente": "#dc2626",
  "moderee": "#d97706",
  "rare": "#16a34a",
};
